//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Cplsvr1.rc
//
#define IDD_GENERIC_REMAP               3
#define IDS_BUTTONS                     7
#define IDS_MAIN                        8
#define IDS_MAPPING                     9
#define IDS_ABOUT                       10
#define IDS_CONFIG                      11
#define IDS_DISABLEFF                   12
#define IDS_DISABLEAX                   13
#define IDS_PORT                        14
#define IDS_TYPE                        15
#define IDS_SCAN                        16
#define IDS_DEATH                       17
#define IDS_ANALOG                      18
#define IDS_ENABLE                      19
#define IDS_PRESSANDKEEP                20
#define IDS_THEN                        21
#define IDS_FINALLY                     22
#define IDS_AXES                        23
#define IDS_UNABLE                      24
#define IDS_MAPPEDAS                    25
#define IDS_UNMAPPED                    26
#define IDS_SUPPORTED                   27
#define IDS_TESTEFFECT                  28
#define IDS_MOTORS                      29
#define IDS_SMALL                       30
#define IDS_BIG                         31
#define IDS_FEEDBACK                    33
#define IDS_STOP                        34
#define IDS_ERRORFF                     35
#define IDS_CONDITION                   36
#define IDS_ALLWAYSANALOG               37
#define IDS_DSHOCK2                     38
#define IDS_CALIBRATE                   39
#define IDS_SPEED                       40
#define IDS_RESPONSE                    41
#define IDS_SCANMODE                    42
#define IDS_ANALOGREMAP                 43
#define IDS_X                           44
#define IDS_Y                           45
#define IDS_Z                           46
#define IDS_RZ                          47
#define IDS_CALIBRATEMSG                48
#define IDS_ANALOGPRESURE               49
#define IDD_CPLSVR1_CONFIG              106
#define IDD_CPLSVR1_FEEDBACK            107
#define IDD_CPLSVR1_ABOUT               108
#define IDB_TELE                        112
#define IDB_PUNTITO                     118
#define IDB_OFF                         121
#define IDB_ON                          122
#define IDB_LON                         124
#define IDB_LOFF                        125
#define IDB_LOGO                        127
#define IDI_BUTTONOFF                   200
#define IDI_BUTTONON                    201
#define IDC_TESTJOYBTNICON              300
#define IDC_TESTJOYBTNICON2             301
#define IDC_TESTJOYBTNICON3             302
#define IDC_TESTJOYBTNICON4             303
#define IDC_TESTJOYBTNICON5             304
#define IDC_TESTJOYBTNICON6             305
#define IDC_TESTJOYBTNICON7             306
#define IDC_TESTJOYBTNICON8             307
#define IDC_TESTJOYBTNICON9             308
#define IDC_TESTJOYBTNICON10            309
#define IDC_TESTJOYBTNICON11            310
#define IDC_TESTJOYBTNICON12            311
#define IDC_TESTJOYBTNICON13            312
#define IDC_TESTJOYBTNICON14            313
#define IDC_TESTJOYBTNICON15            314
#define IDC_TESTJOYBTNICON16            315
#define IDC_RXDATA2                     1005
#define IDC_RYDATA2                     1006
#define IDC_S1DATA2                     1008
#define IDC_S2DATA2                     1009
#define IDC_CALIBRATE                   1030
#define IDC_TELE2                       1031
#define IDC_TELE1                       1032
#define IDC_MAPEDAS                     1034
#define IDC_MAPEDAS2                    1035
#define IDC_MAPEDAS3                    1036
#define IDC_MAPEDAS4                    1037
#define IDC_MAPEDAS5                    1038
#define IDC_MAPEDAS6                    1039
#define IDC_MAPEDAS7                    1040
#define IDC_MAPEDAS8                    1041
#define IDC_MAPEDAS9                    1042
#define IDC_MAPEDAS10                   1043
#define IDC_MAPEDAS11                   1044
#define IDC_MAPEDAS12                   1045
#define IDC_MAPEDAS13                   1046
#define IDC_MAPEDAS14                   1047
#define IDC_MAPEDAS15                   1048
#define IDC_MAPEDAS16                   1049
#define IDC_1                           1050
#define IDC_2                           1051
#define IDC_3                           1052
#define IDC_4                           1053
#define IDC_5                           1054
#define IDC_6                           1055
#define IDC_7                           1056
#define IDC_8                           1057
#define IDC_9                           1058
#define IDC_10                          1059
#define IDC_11                          1060
#define IDC_12                          1061
#define IDC_13                          1062
#define IDC_14                          1063
#define IDC_15                          1064
#define IDC_16                          1065
#define IDC_UNMAPPED                    1066
#define IDC_RESET                       1067
#define IDC_LINEA1                      1068
#define IDC_LINEA2                      1069
#define IDC_LINEA3                      1070
#define IDC_MAPPEDASTEXT                1072
#define IDC_BUTTONS                     1073
#define IDC_TESTEFFECT                  1074
#define IDC_ANALOGPRESURE               1074
#define IDC_BIG                         1075
#define IDC_SMALL                       1076
#define IDC_MOTORSTEST                  1077
#define IDC_BIGTEXT                     1078
#define IDC_SUPPORTED                   1079
#define IDC_DISABLEFF                   1083
#define IDC_DSHOCK2                     1084
#define IDC_DISABLEAX                   1085
#define IDC_ALLWAYSANALOG               1086
#define IDC_SCAN                        1087
#define IDC_DELAY                       1088
#define IDC_DEATHNUM                    1089
#define IDC_AXIS                        1090
#define IDC_ANALOG1                     1091
#define IDC_ANALOG2                     1092
#define IDC_ANALOG3                     1093
#define IDC_ANALOG4                     1094
#define IDC_SCANMODE                    1095
#define IDC_SPEED                       1096
#define IDC_RESPONSE                    1097
#define IDC_ANALOGREMAP                 1098
#define IDC_EJE1                        1099
#define IDC_EJE2                        1100
#define IDC_EJE3                        1101
#define IDC_EJE4                        1102
#define IDC_DEATH                       1103
#define IDC_JOYSTICKID                  1104
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
